### ISSUE TITLE
Does catalog specification need to be CMAF-specific?

### ISSUE THREAD

**Issue by vasilvv** [moq-wg/msf#13]
The document currently specifies both a catalog format, and how to bind CMAF into it.  Do we really need to tie those two?  I can imagine having a catalog that uses CMAF for video, and, say, a lower-overhead format for audio.  I also imagine that the mechanisms for specifying track locations, updating tracks, etc, do not actually depend on the format used, so it may be redundant to group those two.

Back in the warp-draft04, we had the same catalog format for everything, but each track had its own format.  Would that make more sense?

**Comment by wilaw** [comment]
> The document currently specifies both a catalog format, and how to bind CMAF into it. Do we really need to tie those two?

The purpose of the draft is to define a Streaming Format that works with MoQ transport. Any workable "streaming format" requires a number of characteristics to be defined, such as a catalog format (how to describe what you have ), a media packaging format (for example, use CMAF), rules for streaming (for example, send one GOP per stream and increment the send order), rules for signaling the start and end of streams, authentication schemes etc. I anticipate that there is enough desire for catalog differentiation and format diversity, that trying to coerce every distributor to use a single catalog format is going to result in compromises and overhead. 

The catalog format I have define in this draft meets the needs of most sports/live event/game broadcasters using low latency HLS or DASH today. I am reasonably sure it does not have the complexity to meet the needs of someone trying to stream VR or AR content, where there are more spatial and temporal constraints on, and relationships between, the tracks being advertised.  We could work to integrate that complexity in to a common catalog format, but then we'd be carrying of lot of overhead that would be unused for the majority of "simple" streaming cases. As I envision it, having a small number of streaming formats that are simple to implement and that serve different use-cases in the most efficient way possible, is preferable and more extensible than trying to munge everything in to one single catalog format.

> I can imagine having a catalog that uses CMAF for video, and, say, a lower-overhead format for audio.

The catalog format defined currently leverages the convenience of the CMAF init segment to provide dual utility to the client: a concise description of the selection criteria (resolution, codec, bitrate etc) and the init data it needs to begin decoding the track. Since that is not immediately available with something like Ogg/Opus, we'd need to extend the catalog definition to allow alternate means for specifying the selection criteria and initializing the decoder. I'm not against this at all. The current draft is a direct extension of Luke's work on WARP, which constrained the packaging to CMAF. If there is WG consensus that we want to support alternate packaging formats under the WARP umbrella, then we can easily do that. We can also publish WARP as a CMAF-only streaming format and then create another streaming format that leverages multiple container types.

**Comment by vasilvv** [comment]
> The catalog format I have define in this draft meets the needs of most sports/live event/game broadcasters using low latency HLS or DASH today. I am reasonably sure it does not have the complexity to meet the needs of someone trying to stream VR or AR content, where there are more spatial and temporal constraints on, and relationships between, the tracks being advertised.

Sure, but I feel like the general problem of "how do I encode adding or removing tracks" and "how do I encode relationship between two tracks" is general enough that it would make more sense to define a common format for those, and then leave the specifics sufficiently extensible that the other formats can use those to build whatever they need.

**Comment by wilaw** [comment]
> Sure, but I feel like the general problem of "how do I encode adding or removing tracks" and "how do I encode relationship between two tracks" is general enough that it would make more sense to define a common format for those, and then leave the specifics sufficiently extensible that the other formats can use those to build whatever they need.

OK, so we could create a core catalog definition which all streaming formats then inherit and extend.  It would have elemental methods of add, delete tracks and some sort of ID to identify the streaming format being used.  The add() and remove() methods would contain streaming-format specific payloads. The relationship and dependencies between tracks could be expressed within those payloads, as well as initialization and selection data. This seems like something that could be added to the core moq-transport spec, if it is to be used consistently by all moq streaming formats?

**Comment by vasilvv** [comment]
> This seems like something that could be added to the core moq-transport spec, if it is to be used consistently by all moq streaming formats?

I think we've agreed before that moq-transport is for things that intermediaries might need to know about, so that probably does not belong there.  I'd start by moving catalog and CMAF bindings on top of it into a different sections, and then possibly discuss whether those need to be separate drafts.  Should I try writing a PR to see how this would look?

**Comment by wilaw** [comment]
@Victor - yes, please go ahead with a PR. In parallel, I am preparing a proposal for a new catalog format that would be a harmonized catalog between WARP and LOC. It will have the following attributes
1. Common catalog structure with versioning and extensibility
2. External reference to a packaging draft. -so CMAF and LOC can be used interchangeably.
3. The add/remove track features of WARP
4. Inheritance, for compactness
5. Track relations from LOC
6. Catalog delta updates from WARP

**Comment by victor** [comment]
please be careful with your @-mentions

**Comment by wilaw** [comment]
A [catalog draft ](https://datatracker.ietf.org/doc/draft-wilaw-moq-catalogformat/ )has been developed , which is packaging agnostic. It has code points for CMAF and LOC but could support any number of packaging formats. 

CMAF specific packaging has been broken out in to its own [draft.](https://datatracker.ietf.org/doc/draft-wilaw-moq-cmafpackaging/)

PR#[19](https://github.com/moq-wg/warp-streaming-format/pull/19)  updated  WARP Streaming Format to reference an external catalog definition

PR[#20](https://github.com/moq-wg/warp-streaming-format/pull/20) Modifies document to reference external CMAF packaging draft

These actions address the OP.

@vasilvv  - can this issue be closed as fixed?
