### ISSUE TITLE
Track Description needs to capture media format information

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/msf#2]
Not sure if this belong here or in the base catalog spec though

**Comment by wilaw** [comment]
The base spec should be agnostic to media, therefore anything media related should be defined in a Media Format.

The track description defined for this spec does capture media format information `The init payload in each track descriptor MUST consist of a File Type Box (ftyp) followed by a Movie Box (moov)`. That moov box contains the media format information (resolution, codec, timebase) that the client needs to both select the track and initialize its decoder. 

The only issue outstanding is perhaps the max bitrate. It's not clear that that is consistently signalled within the moov atom. In that case, we would need to add an explicit field in the Track Descriptor to signal max bitrate?

**Comment by wilaw** [comment]
The base catalog spec at https://datatracker.ietf.org/doc/draft-wilaw-moq-catalogformat/ now defines multiple "content selection parameters", including

Dependencies
Certain tracks may depend on other tracks for decoding. Dependencies holds an array of track names Section 3.2.10 on which the current track is dependent. 

Temporal ID
A number identifying the temporal layer/sub-layer encoding of the track, starting with 0 for the base layer, and increasing with higher temporal fidelity.

Spatial ID
A number identifying the spatial layer encoding of the track, starting with 0 for the base layer, and increasing with higher fidelity.

Codec
A string defining the codec used to encode the track. For LOC packaged content, the string codec registrations are defined in Sect 3 and Section 4 of [WEBCODECS-CODEC-REGISTRY]. For CMAF packaged content, the string codec registrations are defined in XXX.

Mimetype
A string defining the mime type [MIME] of the track. This parameter is typically supplied with CMAF packaged content.

Framerate
A number defining the framerate of the track, expressed as frames per second.

Bitrate
A number defining the bitrate of track, expressed in bits second.

Width
A number expressing the encoded width of the track content in pixels.

Height
A number expressing the encoded height of the video frames in pixels.

Audio sample rate
The number of audio frame samples per second. This property SHOULD only accompany audio codecs.

Channel configuration
A string specifying the audio channel configuration. This property SHOULD only accompany audio codecs. A string is used in order to provide the flexibility to describe complex channel configurations for multi-channel and Next Generation Audio schemas.

Display width
A number expressing the intended display width of the track content in pixels.

Display height
A number expressing the intended display height of the track content in pixels.

Language

**Comment by wilaw** [comment]
@suhasHere  - can this issue be closed given the content selection parameters defined above?

**Comment by wilaw** [comment]
Closing as fixed by selection properties fields of the Common Catalog Format.
